[package]
name = "sas2parquet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "51.0.0"
chrono = "0.4.38"
encoding_rs = "0.8.34"
lazy_static = "1.4.0"
memmap2 = "0.9.4"
rayon = "1.10.0"
